/** @type {import('next').NextConfig} */
const nextConfig = {
  output: 'export',
  // Nécessaire car l'URL de votre site est itmoulchi.github.io/HRStherapie/
  basePath: '/HRStherapie',
  images: {
    unoptimized: true, // Désactive l'optimisation serveur pour les sites statiques GitHub Pages
  },
};

export default nextConfig;
