/** @type {import('next').NextConfig} */
const nextConfig = {
  output: 'export',
  // Ajoute le nom du dépôt au début des chemins d'images et de ressources
  basePath: '/HRStherapie',
  images: {
    unoptimized: true,
  },
  typescript: {
    ignoreBuildErrors: true,
  },
  eslint: {
    ignoreDuringBuilds: true,
  },
};

export default nextConfig;
